### ISSUE TITLE
Docs bug: "recent cryptanalysis" link is broken

### ISSUE THREAD

**Issue by Groxx** [capitalone/fpe#16]
<img width="472" alt="screen shot 2018-05-22 at 2 53 47 pm" src="https://user-images.githubusercontent.com/77197/40392296-f8683fac-5dcf-11e8-9b61-5a26ad8bbd55.png">

Is there a (more stable) mirror that can be linked to instead?

**Comment by anitgandhi** [comment]
Guess I didn't realize I used the NIST's beta website link.

Here's the fixed one: https://csrc.nist.gov/News/2017/Recent-Cryptanalysis-of-FF3

**Comment by Groxx** [comment]
thank you!
