### ISSUE TITLE
The difference between output and input length of FPE

### ISSUE THREAD

**Issue by avahedp** [capitalone/fpe#20]
## Description of Issue
Hi Anit,
I have a variable with 16 to 19 Byte length (PAN) within a message with maximum 37 Byte length (Track2). I want to know if it is possible to use FPE to encrypt this variable (PAN) without any change in message (Track2) format. From the contents of "NIST SP 800-38g" document, it appears that FPE uses AES 128-bit block ciphers. As a result, for encrypting a 19 Byte variable, it will change the message format and will use 32 Byte instead of 19 Byte in Track2 message. (Each 128bit is equal to 16 Byte and for encrypting 19 Byte, we need two 128-bit blocks).
I want to make sure if my explanation is correct. With this assumption, the format of the message will not be preserved.
I am looking forward to hearing from you.
Best Regards.

## Steps to Reproduce

If applicable, mention which version(s) of Go you are able to reproduce this on, along with `go env` output.

**Comment by anitgandhi** [comment]
While FPE does use AES as its underlying block cipher, this fact is abstracted from the user. For a given `radix` input, format and length of the input are preserved in the output. I don't personally have experience with Track2, but the way FPE works is that if you pass in a string of length 19, your output will be of length 19.

**Comment by avahedp** [comment]
Thank you very much indeed.
