### ISSUE TITLE
Root repo directory is not a valid Go package

### ISSUE THREAD

**Issue by SamWhited** [capitalone/fpe#6]
The root repo directory is not a valid Go package because it does not contain any Go files. This means that the link to godoc.org in the Readme (the badge) is broken and `go get` cannot be used to fetch it directly (which may or may not be a problem). Maybe the badge should point to the `ff1` or `ff3` packages instead, or a `doc.go` should be added to the root repo directory purely to give some context and link to the subdirectories?

**Comment by SamWhited** [comment]
Apologies, the GDDO link is no longer broken. It does correctly generate a page if you visit the subpackages first. The error is just confusing; might file an issue upstream about this.

**Comment by anitgandhi** [comment]
Thanks for pointing that out. I was wondering why godoc wasn't showing it for so long.

I will make it more clear in the README that it should be pulled with `go get github.com/capitalone/for/...`. 

Perhaps adding an empty `fpe.go` would also help?

**Comment by SamWhited** [comment]
> Perhaps adding an empty fpe.go would also help?

It would, this would also mean you could pull the entire tree with `go get github.com/capitalone/fpe`.
If you're not adding anything else and it's just for the purpose of showing documentation on GDDO, convention is to include a file called `doc.go` that simply includes a package declaration and the docs you want.

I'm not sure it's necessary though since the directories do show up on GDDO now though (and you probably don't want people accidentally doing `import github.com/capitalone/fpe` and then wondering why there's nothing there).

**Comment by cstockton** [comment]
You could always put a doc.go file in the project root with a package doc block describing the repo overall like the readme. Then you get a nice link to each subpkg on the godoc page. i.e.:

- **doc.go**
> ```Go
> // Package fpe implements the NIST approved Format Preserving Encryption (FPE) FF1 and FF3 algorithms.
> //
> // FPE
> // <fpe is..>
> //
> // FF1
> // The FF1 gets rendered in a nice bold heading and below these comments will be a list of subpackages.
> package fpe
> ```
